config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'rps#index'

  resource :rps, only: :index
  get '/throw', to: 'rps#throw'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game_session.rb
# frozen_string_literal: true

class GameSession < ApplicationRecord
  validates :user_throw, :server_throw, :status, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/rps_controller.rb
# frozen_string_literal: true

class RpsController < ApplicationController
  STATUSES = {
    won: :success,
    lost: :danger,
    draw: :warning
  }.freeze

  def index
    @statistic = Rps::Statistic.call
  end

  def throw
    @result = Rps::Play.call(params[:user_throw])
    flash[STATUSES[@result.status]] = "You #{@result.status}, opponent threw #{@result.server_throw}"
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rps</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div class="alert alert-<%= type %>">
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/rps/index.html.erb
<div class='container-md text-center'>
  <h2 class='title'>ROCK – PAPER – SCISSORS</h2>

  <p class='descr'>Rock Paper Scissors is a zero sum game that is usually played by two people using their hands and no tools. The idea is to make shapes with an outstretched hand where each shape will have a certain degree of power and will lead to an outcome.</p>

  <p><strong>SELECT YOUR BET</strong></p>

  <h1>Statistic:</h1>

  <p>User wins: <%= @statistic[:user_wins] %></p>
  <p>Server wins: <%= @statistic[:server_wins] %></p>
  <p>Win percentage: <%= @statistic[:win_percentage] %></p>

  <div class='row align-items-start'>
    <div class="col-4">
      <%= link_to throw_path(user_throw: 'rock') do %>
        <div class="card throw-card">
          <%= image_tag 'Rock', size: '250x250', class: 'rounded mx-auto d-block' %>
          <div class="card-body">
            <div class="card-text">
              Rock
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-4">
      <%= link_to throw_path(user_throw: 'paper') do %>
        <div class="card throw-card">
          <%= image_tag 'Paper', size: '250x250', class: 'rounded mx-auto d-block' %>
          <div class="card-body">
            <div class="card-text">
              Paper
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-4">
      <%= link_to throw_path(user_throw: 'scissors') do %>
        <div class="card throw-card">
          <%= image_tag 'Scissors', size: '250x250', class: 'rounded mx-auto d-block' %>
          <div class="card-body">
            <div class="card-text">
              Scissors
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>